webtalk_init -webtalk_dir C:/Users/94762/stuff/Notes/computer_organization/niman/lab3to7/temp_/nano_processor/nano_processor.sim/sim_1/behav/xsim/xsim.dir/TB_nano_processor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun 11 19:43:56 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a6ee99b3-7ee2-44fa-817a-c17553c0f923" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1cc8c7eaafa2498cbe0374325fe07109" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "119" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2803 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "23" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "98 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "10 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "176" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "55" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.47_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "53536_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3247914515 -regid "" -xml C:/Users/94762/stuff/Notes/computer_organization/niman/lab3to7/temp_/nano_processor/nano_processor.sim/sim_1/behav/xsim/xsim.dir/TB_nano_processor_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/94762/stuff/Notes/computer_organization/niman/lab3to7/temp_/nano_processor/nano_processor.sim/sim_1/behav/xsim/xsim.dir/TB_nano_processor_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/94762/stuff/Notes/computer_organization/niman/lab3to7/temp_/nano_processor/nano_processor.sim/sim_1/behav/xsim/xsim.dir/TB_nano_processor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
